name: CI
...
build:
runs-on: ubuntu-latest
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
- uses: actions/checkout@v2
# Runs a set of commands using the runners shell
- name: Build and Push
#env:
#DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
run: |
cd master/chapter9 && echo "Build Docker Image"
#docker login -u kaizheh -p ${DOCKER_SECRET}
docker build -t kaizheh/anchore-cli . && docker push
kaizheh/anchore-cli
